"""
Django settings for the WorkoutWare project.

This module defines global configuration for the Django application,
including:

- Installed apps
- Middleware components
- Template rendering engines
- Authentication and session management
- Static and media file handling
- Database configuration (MySQL via Docker container)
- Security and deployment settings

The file reads optional overrides from `local_settings.py` when present.
It is the central configuration file that controls how the framework behaves.

================================================================================
SETUP INSTRUCTIONS - DATABASE CONFIGURATION
================================================================================

DATABASE SETUP REQUIREMENTS:
    1. MySQL 8.0 must be running (via Docker or local installation)
    2. Database 'workoutware' must exist (created via sql/workoutware_db_setup.sql)
    3. MySQL user must have appropriate permissions

DEFAULT DATABASE CONFIGURATION:
    - Database Name: workoutware
    - User: root
    - Password: Rutgers123 (CHANGE IN PRODUCTION!)
    - Host: 127.0.0.1 (localhost)
    - Port: 3306

TO MODIFY DATABASE SETTINGS:
    1. Edit the DATABASES dictionary below (lines 97-109)
    2. Or create a local_settings.py file in this directory with:
       DATABASES = {
           'default': {
               'ENGINE': 'django.db.backends.mysql',
               'NAME': 'your_database_name',
               'USER': 'your_username',
               'PASSWORD': 'your_password',
               'HOST': 'your_host',
               'PORT': 'your_port',
           }
       }

DOCKER MYSQL SETUP:
    docker pull mysql:8.0
    docker run --name workoutware -e MYSQL_ROOT_PASSWORD=Rutgers123 -p 3306:3306 -d mysql:8.0

VERIFY DATABASE CONNECTION:
    After setup, test connection with:
    python manage.py dbshell
    (Should connect to MySQL prompt)

SECURITY NOTES:
    - DEBUG=True is set for development only - NEVER use in production
    - SECRET_KEY should be changed for production deployments
    - Database password should be stored in environment variables in production
"""
"""
Django settings for workoutware project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l)o)14iwln%kpz6c-b7odhqd686y2p4!0fllo*3m@)kn*spn6i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'workoutware_app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'workoutware.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

WSGI_APPLICATION = 'workoutware.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'workoutware',
        'USER': 'root',
        'PASSWORD': 'Rutgers123',
        'HOST': '127.0.0.1',     # Important!
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Local override for SQLite
try:
    from .local_settings import *
except ImportError:
    pass


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

