# Generated by Django 5.2.7 on 2025-12-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_validation',
            fields=[
                ('validation_id', models.AutoField(primary_key=True, serialize=False)),
                ('input_weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('expected_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('flagged_as', models.CharField(blank=True, max_length=20, null=True)),
                ('user_action', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'data_validation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='exercise',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('subtype', models.CharField(blank=True, max_length=50, null=True)),
                ('equipment', models.CharField(blank=True, max_length=50, null=True)),
                ('difficulty', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('demo_link', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'exercise',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='exercise_target_association',
            fields=[
                ('association_id', models.AutoField(primary_key=True, serialize=False)),
                ('intensity', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'exercise_target_association',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='goals',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('goal_type', models.CharField(max_length=100)),
                ('goal_description', models.TextField(blank=True, null=True)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('unit', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('completion_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'goals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='progress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('period_type', models.CharField(max_length=20)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('avg_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('workout_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'progress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='session_exercises',
            fields=[
                ('session_exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise_order', models.IntegerField()),
                ('target_sets', models.IntegerField(blank=True, null=True)),
                ('target_reps', models.IntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'session_exercises',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='sets',
            fields=[
                ('set_id', models.AutoField(primary_key=True, serialize=False)),
                ('set_number', models.IntegerField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('rpe', models.IntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=True)),
                ('is_warmup', models.BooleanField(blank=True, default=False, null=True)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='target',
            fields=[
                ('target_id', models.AutoField(primary_key=True, serialize=False)),
                ('target_name', models.CharField(max_length=50)),
                ('target_group', models.CharField(max_length=50)),
                ('target_function', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'target',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('town', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('password_hash', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_registered', models.DateField(blank=True, null=True)),
                ('date_unregistered', models.DateField(blank=True, null=True)),
                ('registered', models.BooleanField(default=True)),
                ('fitness_goal', models.CharField(blank=True, max_length=50, null=True)),
                ('user_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'user_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='user_pb',
            fields=[
                ('pr_id', models.AutoField(primary_key=True, serialize=False)),
                ('pr_type', models.CharField(max_length=20)),
                ('pb_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pb_reps', models.IntegerField(blank=True, null=True)),
                ('pb_time', models.TimeField(blank=True, null=True)),
                ('pb_date', models.DateField()),
                ('previous_pr', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_pb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='user_stats_log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('neck', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('waist', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hips', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_stats_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='workout_goal_link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workout_goal_link',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='workout_plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_description', models.TextField(blank=True, null=True)),
                ('plan_type', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_days', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workout_plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='workout_sessions',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_name', models.CharField(blank=True, max_length=100, null=True)),
                ('session_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('bodyweight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('is_template', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'workout_sessions',
                'managed': False,
            },
        ),
    ]
