# Generated by Django 5.2.7 on 2025-11-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workoutware_app", "0005_alter_exercise_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="data_validation",
            fields=[
                ("validation_id", models.AutoField(primary_key=True, serialize=False)),
                ("input_weight", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "expected_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("flagged_as", models.CharField(blank=True, max_length=20, null=True)),
                ("user_action", models.CharField(blank=True, max_length=20, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "data_validation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="progress",
            fields=[
                ("metric_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("period_type", models.CharField(max_length=20)),
                (
                    "max_weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "avg_weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "total_volume",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("workout_count", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "progress",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="session_exercises",
            fields=[
                (
                    "session_exercise_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("exercise_order", models.IntegerField()),
                ("target_sets", models.IntegerField(blank=True, null=True)),
                ("target_reps", models.IntegerField(blank=True, null=True)),
                ("completed", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "session_exercises",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="sets",
            fields=[
                ("set_id", models.AutoField(primary_key=True, serialize=False)),
                ("set_number", models.IntegerField()),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("reps", models.IntegerField(blank=True, null=True)),
                ("rpe", models.IntegerField(blank=True, null=True)),
                ("completed", models.BooleanField(default=True)),
                (
                    "is_warmup",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("completion_time", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "sets",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="workout_sessions",
            fields=[
                ("session_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "session_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("session_date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                (
                    "bodyweight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("completed", models.BooleanField(default=True)),
                ("is_template", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "workout_sessions",
                "managed": False,
            },
        ),
    ]
