# Generated by Django 5.2.7 on 2025-12-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workoutware_app",
            "0006_data_validation_progress_session_exercises_sets_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="goals",
            fields=[
                ("goal_id", models.AutoField(primary_key=True, serialize=False)),
                ("goal_type", models.CharField(max_length=100)),
                ("goal_description", models.TextField(blank=True, null=True)),
                ("target_value", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("unit", models.CharField(max_length=20)),
                ("start_date", models.DateField()),
                ("target_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="active", max_length=50)),
                ("completion_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "goals",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="user_pb",
            fields=[
                ("pr_id", models.AutoField(primary_key=True, serialize=False)),
                ("pr_type", models.CharField(max_length=20)),
                (
                    "pb_weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("pb_reps", models.IntegerField(blank=True, null=True)),
                ("pb_time", models.TimeField(blank=True, null=True)),
                ("pb_date", models.DateField()),
                (
                    "previous_pr",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_pb",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="user_stats_log",
            fields=[
                ("log_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("weight", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "neck",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "waist",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "hips",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "body_fat_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_stats_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="workout_plan",
            fields=[
                ("plan_id", models.AutoField(primary_key=True, serialize=False)),
                ("plan_description", models.TextField(blank=True, null=True)),
                ("plan_type", models.CharField(blank=True, max_length=50, null=True)),
                ("number_of_days", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "workout_plan",
                "managed": False,
            },
        ),
    ]
