# Generated by Django 5.2.7 on 2025-12-04 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workoutware_app", "0007_goals_user_pb_user_stats_log_workout_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="exercise_target_association",
            fields=[
                ("association_id", models.AutoField(primary_key=True, serialize=False)),
                ("intensity", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "db_table": "exercise_target_association",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="target",
            fields=[
                ("target_id", models.AutoField(primary_key=True, serialize=False)),
                ("target_name", models.CharField(max_length=50)),
                ("target_group", models.CharField(max_length=50)),
                ("target_function", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "target",
                "managed": False,
            },
        ),
    ]
