# Generated by Django 5.2.7 on 2025-12-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workoutware_app", "0008_exercise_target_association_target"),
    ]

    operations = [
        migrations.CreateModel(
            name="workout_goal_link",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "workout_goal_link",
                "managed": False,
            },
        ),
    ]
